#include "base.h"
#include "journey.h"
#include <stdlib.h>
#include <windows.h>
#include <iostream>
using namespace std;
void base()
{
    system("COLOR 1F");
    system("cls");
    cout << "########################" << endl;
    cout << "#                      #" << endl;
    cout << "#                       " << endl;
    cout << "#                       " << endl;
    cout << "#                       " << endl;
    cout << "#  0                    " << endl;
    cout << "# -|-                   " << endl;
    cout << "########################" << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << "You are at your base, one of the only safe places in this wasteland. " << endl;
    cout << "Commands: " << endl;
    cout << "L = leave base and enter wasteland";
    cout << endl;
    for( ; ; )
    {
        if(GetAsyncKeyState('L'))
        {
         cout << "########################" << endl;
         cout << "#                      #" << endl;
         cout << "#                       " << endl;
         cout << "#                       " << endl;
         cout << "#                       " << endl;
         cout << "#   0                   " << endl;
         cout << "#  -|-                  " << endl;
         cout << "########################" << endl;
         Sleep(30);
         system("cls");
         cout << "########################" << endl;
         cout << "#                      #" << endl;
         cout << "#                       " << endl;
         cout << "#                       " << endl;
         cout << "#                       " << endl;
         cout << "#    0                  " << endl;
         cout << "#   -|-                 " << endl;
         cout << "########################" << endl;
         Sleep(30);
         system("cls");
         cout << "########################" << endl;
         cout << "#                      #" << endl;
         cout << "#                       " << endl;
         cout << "#                       " << endl;
         cout << "#                       " << endl;
         cout << "#     0                " << endl;
         cout << "#    -|-               " << endl;
         cout << "########################" << endl;
         Sleep(30);
         system("cls");
         cout << "########################" << endl;
         cout << "#                      #" << endl;
         cout << "#                       " << endl;
         cout << "#                       " << endl;
         cout << "#                       " << endl;
         cout << "#      0                " << endl;
         cout << "#     -|-               " << endl;
         cout << "########################" << endl;
         Sleep(30);
         system("cls");
         cout << "########################" << endl;
         cout << "#                      #" << endl;
         cout << "#                       " << endl;
         cout << "#                       " << endl;
         cout << "#                       " << endl;
         cout << "#       0               " << endl;
         cout << "#      -|-              " << endl;
         cout << "########################" << endl;
         Sleep(30);
         system("cls");
         cout << "########################" << endl;
         cout << "#                      #" << endl;
         cout << "#                       " << endl;
         cout << "#                       " << endl;
         cout << "#                       " << endl;
         cout << "#        0              " << endl;
         cout << "#       -|-             " << endl;
         cout << "########################" << endl;
         Sleep(30);
         system("cls");
         cout << "########################" << endl;
         cout << "#                      #" << endl;
         cout << "#                       " << endl;
         cout << "#                       " << endl;
         cout << "#                       " << endl;
         cout << "#         0             " << endl;
         cout << "#        -|-            " << endl;
         cout << "########################" << endl;
         Sleep(30);
         system("cls");
         cout << "########################" << endl;
         cout << "#                      #" << endl;
         cout << "#                       " << endl;
         cout << "#                       " << endl;
         cout << "#                       " << endl;
         cout << "#          0            " << endl;
         cout << "#         -|-           " << endl;
         cout << "########################" << endl;
         Sleep(30);
         system("cls");
         cout << "########################" << endl;
         cout << "#                      #" << endl;
         cout << "#                       " << endl;
         cout << "#                       " << endl;
         cout << "#                       " << endl;
         cout << "#           0           " << endl;
         cout << "#          -|-          " << endl;
         cout << "########################" << endl;
         Sleep(30);
         system("cls");
         cout << "########################" << endl;
         cout << "#                      #" << endl;
         cout << "#                       " << endl;
         cout << "#                       " << endl;
         cout << "#                       " << endl;
         cout << "#            0          " << endl;
         cout << "#           -|-         " << endl;
         cout << "########################" << endl;
         Sleep(30);
         system("cls");
         cout << "########################" << endl;
         cout << "#                      #" << endl;
         cout << "#                       " << endl;
         cout << "#                       " << endl;
         cout << "#                       " << endl;
         cout << "#             0         " << endl;
         cout << "#            -|-        " << endl;
         cout << "########################" << endl;
         Sleep(30);
         system("cls");
         cout << "########################" << endl;
         cout << "#                      #" << endl;
         cout << "#                       " << endl;
         cout << "#                       " << endl;
         cout << "#                       " << endl;
         cout << "#              0        " << endl;
         cout << "#             -|-       " << endl;
         cout << "########################" << endl;
         Sleep(30);
         system("cls");
         cout << "########################" << endl;
         cout << "#                      #" << endl;
         cout << "#                       " << endl;
         cout << "#                       " << endl;
         cout << "#                       " << endl;
         cout << "#               0       " << endl;
         cout << "#              -|-      " << endl;
         cout << "########################" << endl;
         Sleep(30);
         system("cls");
         cout << "########################" << endl;
         cout << "#                      #" << endl;
         cout << "#                       " << endl;
         cout << "#                       " << endl;
         cout << "#                       " << endl;
         cout << "#                0      " << endl;
         cout << "#               -|-     " << endl;
         cout << "########################" << endl;
         Sleep(30);
         system("cls");
         cout << "########################" << endl;
         cout << "#                      #" << endl;
         cout << "#                       " << endl;
         cout << "#                       " << endl;
         cout << "#                       " << endl;
         cout << "#                 0     " << endl;
         cout << "#                -|-    " << endl;
         cout << "########################" << endl;
         Sleep(30);
         system("cls");
         cout << "########################" << endl;
         cout << "#                      #" << endl;
         cout << "#                       " << endl;
         cout << "#                       " << endl;
         cout << "#                       " << endl;
         cout << "#                  0    " << endl;
         cout << "#                 -|-   " << endl;
         cout << "########################" << endl;
         Sleep(30);
         system("cls");
         cout << "########################" << endl;
         cout << "#                      #" << endl;
         cout << "#                       " << endl;
         cout << "#                       " << endl;
         cout << "#                       " << endl;
         cout << "#                   0   " << endl;
         cout << "#                  -|-  " << endl;
         cout << "########################" << endl;
         Sleep(30);
         system("cls");
         cout << "########################" << endl;
         cout << "#                      #" << endl;
         cout << "#                       " << endl;
         cout << "#                       " << endl;
         cout << "#                       " << endl;
         cout << "#                    0  " << endl;
         cout << "#                   -|- " << endl;
         cout << "########################" << endl;
         Sleep(30);
         system("cls");
         cout << "########################" << endl;
         cout << "#                      #" << endl;
         cout << "#                       " << endl;
         cout << "#                       " << endl;
         cout << "#                       " << endl;
         cout << "#                     0 " << endl;
         cout << "#                    -|-" << endl;
         cout << "########################" << endl;
         Sleep(30);
         system("cls");
         cout << "########################" << endl;
         cout << "#                      #" << endl;
         cout << "#                       " << endl;
         cout << "#                       " << endl;
         cout << "#                       " << endl;
         cout << "#                       " << endl;
         cout << "#                       " << endl;
         cout << "########################" << endl;
         Sleep(500);
         walk();

        }
    }
}
