#include "journey.h"
#include "base.h"
#include "zombie.h"
#include "town.h"
#include <iostream>
#include <stdlib.h>
#include <windows.h>
using namespace std;
void walk()
{
    system("COLOR 1F");
    char choice;
    double kilo = 0.5;
    int chance;
    for( ; ; )
    {
         cout << "                        " << endl;
         cout << "                        " << endl;
         cout << "                        " << endl;
         cout << "                        " << endl;
         cout << " 0                      " << endl;
         cout << "-|-                     " << endl;
         cout << "########################" << endl;
         Sleep(30);
         system("cls");
         cout << "                        " << endl;
         cout << "                        " << endl;
         cout << "                        " << endl;
         cout << "                        " << endl;
         cout << "  0                      " << endl;
         cout << " -|-                     " << endl;
         cout << "########################" << endl;
         Sleep(30);
         system("cls");
         cout << "                        " << endl;
         cout << "                        " << endl;
         cout << "                        " << endl;
         cout << "                        " << endl;
         cout << "   0                      " << endl;
         cout << "  -|-                     " << endl;
         cout << "########################" << endl;
         Sleep(30);
         system("cls");
         cout << "                        " << endl;
         cout << "                        " << endl;
         cout << "                        " << endl;
         cout << "                        " << endl;
         cout << "   0                      " << endl;
         cout << "  -|-                     " << endl;
         cout << "########################" << endl;
         Sleep(30);
         system("cls");
         cout << "                        " << endl;
         cout << "                        " << endl;
         cout << "                        " << endl;
         cout << "                        " << endl;
         cout << "    0                      " << endl;
         cout << "   -|-                     " << endl;
         cout << "########################" << endl;
         Sleep(30);
         system("cls");
         cout << "                        " << endl;
         cout << "                        " << endl;
         cout << "                        " << endl;
         cout << "                        " << endl;
         cout << "     0                      " << endl;
         cout << "    -|-                     " << endl;
         cout << "########################" << endl;
         Sleep(30);
         system("cls");
         cout << "                        " << endl;
         cout << "                        " << endl;
         cout << "                        " << endl;
         cout << "                        " << endl;
         cout << "      0                      " << endl;
         cout << "     -|-                     " << endl;
         cout << "########################" << endl;
         Sleep(30);
         system("cls");
         cout << "                        " << endl;
         cout << "                        " << endl;
         cout << "                        " << endl;
         cout << "                        " << endl;
         cout << "       0                      " << endl;
         cout << "      -|-                     " << endl;
         cout << "########################" << endl;
         Sleep(30);
         system("cls");
         cout << "                        " << endl;
         cout << "                        " << endl;
         cout << "                        " << endl;
         cout << "                        " << endl;
         cout << "        0                      " << endl;
         cout << "       -|-                     " << endl;
         cout << "########################" << endl;
         Sleep(30);
         system("cls");
         cout << "                        " << endl;
         cout << "                        " << endl;
         cout << "                        " << endl;
         cout << "                        " << endl;
         cout << "         0                      " << endl;
         cout << "        -|-                     " << endl;
         cout << "########################" << endl;
         Sleep(30);
         system("cls");
         cout << "                        " << endl;
         cout << "                        " << endl;
         cout << "                        " << endl;
         cout << "                        " << endl;
         cout << "          0                      " << endl;
         cout << "         -|-                     " << endl;
         cout << "########################" << endl;
         Sleep(30);
         system("cls");
         cout << "                        " << endl;
         cout << "                        " << endl;
         cout << "                        " << endl;
         cout << "                        " << endl;
         cout << "           0            " << endl;
         cout << "          -|-           " << endl;
         cout << "########################" << endl;
         Sleep(30);
         system("cls");
         cout << "                        " << endl;
         cout << "                        " << endl;
         cout << "                        " << endl;
         cout << "                        " << endl;
         cout << "            0           " << endl;
         cout << "           -|-          " << endl;
         cout << "########################" << endl;
         Sleep(30);
         cout << "Kilometors from base: " << kilo << endl;
         cout << "You are in th middle of the wasteland." << endl;
         cout << "Commands: " << endl;
         cout << "R: Return to base. K: Keep going: ";
         cin >> choice;
         if(choice == 'K')
         {
          cout << "                        " << endl;
          cout << "                        " << endl;
          cout << "                        " << endl;
          cout << "                        " << endl;
          cout << "             0            " << endl;
          cout << "            -|-           " << endl;
          cout << "########################" << endl;
          Sleep(30);
          system("cls");
          cout << "                        " << endl;
          cout << "                        " << endl;
          cout << "                        " << endl;
          cout << "                        " << endl;
          cout << "              0            " << endl;
          cout << "             -|-           " << endl;
          cout << "########################" << endl;
          Sleep(30);
          system("cls");
          cout << "                        " << endl;
          cout << "                        " << endl;
          cout << "                        " << endl;
          cout << "                        " << endl;
          cout << "               0            " << endl;
          cout << "              -|-           " << endl;
          cout << "########################" << endl;
          Sleep(30);
          system("cls");
          cout << "                        " << endl;
          cout << "                        " << endl;
          cout << "                        " << endl;
          cout << "                        " << endl;
          cout << "                0            " << endl;
          cout << "               -|-           " << endl;
          cout << "########################" << endl;
          Sleep(30);
          system("cls");
          cout << "                        " << endl;
          cout << "                        " << endl;
          cout << "                        " << endl;
          cout << "                        " << endl;
          cout << "                 0            " << endl;
          cout << "                -|-           " << endl;
          cout << "########################" << endl;
          Sleep(30);
          system("cls");
          cout << "                        " << endl;
          cout << "                        " << endl;
          cout << "                        " << endl;
          cout << "                        " << endl;
          cout << "                  0            " << endl;
          cout << "                 -|-           " << endl;
          cout << "########################" << endl;
          Sleep(30);
          system("cls");
          cout << "                        " << endl;
          cout << "                        " << endl;
          cout << "                        " << endl;
          cout << "                        " << endl;
          cout << "                    0            " << endl;
          cout << "                   -|-           " << endl;
          cout << "########################" << endl;
          Sleep(30);
          system("cls");
          cout << "                        " << endl;
          cout << "                        " << endl;
          cout << "                        " << endl;
          cout << "                        " << endl;
          cout << "                     0            " << endl;
          cout << "                    -|-           " << endl;
          cout << "########################" << endl;
          Sleep(30);
          system("cls");
          cout << "                        " << endl;
          cout << "                        " << endl;
          cout << "                        " << endl;
          cout << "                        " << endl;
          cout << "                      0            " << endl;
          cout << "                     -|-           " << endl;
          cout << "########################" << endl;
          Sleep(30);
          system("cls");
          cout << "                        " << endl;
          cout << "                        " << endl;
          cout << "                        " << endl;
          cout << "                        " << endl;
          cout << "                      " << endl;
          cout << "                      " << endl;
          cout << "########################" << endl;
          kilo = kilo + 0.7;
          testChance();
          lookForTown();
          Sleep(200);
          continue;
        }
         else if(choice == 'R')
         {
             kilo = 0;
             base();
         }

    }
}
