#include "town.h"
#include "journey.h"
#include <iostream>
#include <stdio.h>
#include <stdlib.h>
#include <time.h>
#include <windows.h>
using namespace std;

int tchance;
int choice;
void findSettlement()
{
         system("COLOR 1F");
         cout << "              #                      #      " << endl;
         cout << "            #   #                  #   #    " << endl;
         cout << "          #      #               #      #   " << endl;
         cout << "          #      #               #      #   " << endl;
         cout << " 0        #      #               #      #   " << endl;
         cout << "-|-       #      #               #      #   " << endl;
         cout << "############################################" << endl;
         Sleep(50);
         system("cls");
         cout << "              #                      #      " << endl;
         cout << "            #   #                  #   #    " << endl;
         cout << "          #      #               #      #   " << endl;
         cout << "          #      #               #      #   " << endl;
         cout << "  0       #      #               #      #   " << endl;
         cout << " -|-      #      #               #      #   " << endl;
         cout << "############################################" << endl;
         Sleep(50);
         system("cls");
         cout << "              #                      #      " << endl;
         cout << "            #   #                  #   #    " << endl;
         cout << "          #      #               #      #   " << endl;
         cout << "          #      #               #      #   " << endl;
         cout << "    0     #      #               #      #   " << endl;
         cout << "   -|-    #      #               #      #   " << endl;
         cout << "############################################" << endl;
         Sleep(50);
         system("cls");
         cout << "              #                      #      " << endl;
         cout << "            #   #                  #   #    " << endl;
         cout << "          #      #               #      #   " << endl;
         cout << "          #      #               #      #   " << endl;
         cout << "     0    #      #               #      #   " << endl;
         cout << "    -|-   #      #               #      #   " << endl;
         cout << "############################################" << endl;
         cout << "You found an abandoned settlement!" << endl;
         cout << "1: Enter house 1. 2: Enter house 2. 3: Leave settlement" << endl;
         cin >> choice;
         if(choice == 1)
         {
         Sleep(50);
         system("cls");
         cout << "              #                      #      " << endl;
         cout << "            #   #                  #   #    " << endl;
         cout << "          #      #               #      #   " << endl;
         cout << "          #      #               #      #   " << endl;
         cout << "     0    #      #               #      #   " << endl;
         cout << "    -|-   #      #               #      #   " << endl;
         cout << "############################################" << endl;
         Sleep(50);
         system("cls");
         cout << "              #                      #      " << endl;
         cout << "            #   #                  #   #    " << endl;
         cout << "          #      #               #      #   " << endl;
         cout << "          #      #               #      #   " << endl;
         cout << "      0   #      #               #      #   " << endl;
         cout << "     -|-  #      #               #      #   " << endl;
         cout << "############################################" << endl;
         Sleep(50);
         system("cls");
         cout << "              #                      #      " << endl;
         cout << "            #   #                  #   #    " << endl;
         cout << "          #      #               #      #   " << endl;
         cout << "          #      #               #      #   " << endl;
         cout << "       0  #      #               #      #   " << endl;
         cout << "      -|- #      #               #      #   " << endl;
         cout << "############################################" << endl;
         Sleep(50);
         system("cls");
         cout << "              #                      #      " << endl;
         cout << "            #   #                  #   #    " << endl;
         cout << "          #      #               #      #   " << endl;
         cout << "          #      #               #      #   " << endl;
         cout << "        0 #      #               #      #   " << endl;
         cout << "       -|-#      #               #      #   " << endl;
         cout << "############################################" << endl;
         Sleep(50);
         system("cls");
         cout << "              #                      #      " << endl;
         cout << "            #   #                  #   #    " << endl;
         cout << "          #      #               #      #   " << endl;
         cout << "          #      #               #      #   " << endl;
         cout << "          #      #               #      #   " << endl;
         cout << "          #      #               #      #   " << endl;
         cout << "############################################" << endl;
         Sleep(90);
         }

         else if(choice == 2)
         {
             Sleep(50);
         system("cls");
         cout << "              #                      #      " << endl;
         cout << "            #   #                  #   #    " << endl;
         cout << "          #      #               #      #   " << endl;
         cout << "          #      #               #      #   " << endl;
         cout << "     0    #      #               #      #   " << endl;
         cout << "    -|-   #      #               #      #   " << endl;
         cout << "############################################" << endl;
         Sleep(50);
         system("cls");
         cout << "              #                      #      " << endl;
         cout << "            #   #                  #   #    " << endl;
         cout << "          #      #               #      #   " << endl;
         cout << "          #      #               #      #   " << endl;
         cout << "      0   #      #               #      #   " << endl;
         cout << "     -|-  #      #               #      #   " << endl;
         cout << "############################################" << endl;
         Sleep(50);
         system("cls");
         cout << "              #                      #      " << endl;
         cout << "            #   #                  #   #    " << endl;
         cout << "          #      #               #      #   " << endl;
         cout << "          #      #               #      #   " << endl;
         cout << "       0  #      #               #      #   " << endl;
         cout << "      -|- #      #               #      #   " << endl;
         cout << "############################################" << endl;
         Sleep(50);
         system("cls");
         cout << "              #                      #      " << endl;
         cout << "            #   #                  #   #    " << endl;
         cout << "          #      #               #      #   " << endl;
         cout << "          #      #               #      #   " << endl;
         cout << "        0 #      #               #      #   " << endl;
         cout << "       -|-#      #               #      #   " << endl;
         cout << "############################################" << endl;
         Sleep(50);
         system("cls");
         cout << "              #                      #      " << endl;
         cout << "            #   #                  #   #    " << endl;
         cout << "          #      #               #      #   " << endl;
         cout << "          #      #               #      #   " << endl;
         cout << "         0       #               #      #   " << endl;
         cout << "        -|-      #               #      #   " << endl;
         cout << "############################################" << endl;
         Sleep(50);
         system("cls");
         cout << "              #                      #      " << endl;
         cout << "            #   #                  #   #    " << endl;
         cout << "          #      #               #      #   " << endl;
         cout << "          #      #               #      #   " << endl;
         cout << "          0      #               #      #   " << endl;
         cout << "         -|-     #               #      #   " << endl;
         cout << "############################################" << endl;
         Sleep(50);
         system("cls");
         cout << "              #                      #      " << endl;
         cout << "            #   #                  #   #    " << endl;
         cout << "          #      #               #      #   " << endl;
         cout << "          #      #               #      #   " << endl;
         cout << "           0     #               #      #   " << endl;
         cout << "          -|-    #               #      #   " << endl;
         cout << "############################################" << endl;
         Sleep(50);
         system("cls");
         cout << "              #                      #      " << endl;
         cout << "            #   #                  #   #    " << endl;
         cout << "          #      #               #      #   " << endl;
         cout << "          #      #               #      #   " << endl;
         cout << "          #  0   #               #      #   " << endl;
         cout << "          # -|-  #               #      #   " << endl;
         cout << "############################################" << endl;
         Sleep(50);
         system("cls");
         cout << "              #                      #      " << endl;
         cout << "            #   #                  #   #    " << endl;
         cout << "          #      #               #      #   " << endl;
         cout << "          #      #               #      #   " << endl;
         cout << "          #   0  #               #      #   " << endl;
         cout << "          #  -|- #               #      #   " << endl;
         cout << "############################################" << endl;
         Sleep(50);
         system("cls");
         cout << "              #                      #      " << endl;
         cout << "            #   #                  #   #    " << endl;
         cout << "          #      #               #      #   " << endl;
         cout << "          #      #               #      #   " << endl;
         cout << "          #    0 #               #      #   " << endl;
         cout << "          #   -|-#               #      #   " << endl;
         cout << "############################################" << endl;
         Sleep(50);
         system("cls");
         cout << "              #                      #      " << endl;
         cout << "            #   #                  #   #    " << endl;
         cout << "          #      #               #      #   " << endl;
         cout << "          #      #               #      #   " << endl;
         cout << "          #     0                #      #   " << endl;
         cout << "          #    -|-               #      #   " << endl;
         cout << "############################################" << endl;
         Sleep(50);
         system("cls");
         cout << "              #                      #      " << endl;
         cout << "            #   #                  #   #    " << endl;
         cout << "          #      #               #      #   " << endl;
         cout << "          #      #               #      #   " << endl;
         cout << "          #      0               #      #   " << endl;
         cout << "          #     -|-              #      #   " << endl;
         cout << "############################################" << endl;
         Sleep(50);
         system("cls");
         cout << "              #                      #      " << endl;
         cout << "            #   #                  #   #    " << endl;
         cout << "          #      #               #      #   " << endl;
         cout << "          #      #               #      #   " << endl;
         cout << "          #       0              #      #   " << endl;
         cout << "          #      -|-             #      #   " << endl;
         cout << "############################################" << endl;
         Sleep(50);
         system("cls");
         cout << "              #                      #      " << endl;
         cout << "            #   #                  #   #    " << endl;
         cout << "          #      #               #      #   " << endl;
         cout << "          #      #               #      #   " << endl;
         cout << "          #      # 0             #      #   " << endl;
         cout << "          #      #-|-            #      #   " << endl;
         cout << "############################################" << endl;
         Sleep(50);
         system("cls");
         cout << "              #                      #      " << endl;
         cout << "            #   #                  #   #    " << endl;
         cout << "          #      #               #      #   " << endl;
         cout << "          #      #               #      #   " << endl;
         cout << "          #      #  0            #      #   " << endl;
         cout << "          #      # -|-           #      #   " << endl;
         cout << "############################################" << endl;
         Sleep(50);
         system("cls");
         cout << "              #                      #      " << endl;
         cout << "            #   #                  #   #    " << endl;
         cout << "          #      #               #      #   " << endl;
         cout << "          #      #               #      #   " << endl;
         cout << "          #      #   0           #      #   " << endl;
         cout << "          #      #  -|-          #      #   " << endl;
         cout << "############################################" << endl;
         Sleep(50);
         system("cls");
         cout << "              #                      #      " << endl;
         cout << "            #   #                  #   #    " << endl;
         cout << "          #      #               #      #   " << endl;
         cout << "          #      #               #      #   " << endl;
         cout << "          #      #    0          #      #   " << endl;
         cout << "          #      #   -|-         #      #   " << endl;
         cout << "############################################" << endl;
         Sleep(50);
         system("cls");
         cout << "              #                      #      " << endl;
         cout << "            #   #                  #   #    " << endl;
         cout << "          #      #               #      #   " << endl;
         cout << "          #      #               #      #   " << endl;
         cout << "          #      #     0         #      #   " << endl;
         cout << "          #      #    -|-        #      #   " << endl;
         cout << "############################################" << endl;
         Sleep(50);
         system("cls");
         cout << "              #                      #      " << endl;
         cout << "            #   #                  #   #    " << endl;
         cout << "          #      #               #      #   " << endl;
         cout << "          #      #               #      #   " << endl;
         cout << "          #      #      0        #      #   " << endl;
         cout << "          #      #     -|-       #      #   " << endl;
         cout << "############################################" << endl;
         Sleep(50);
         system("cls");
         cout << "              #                      #      " << endl;
         cout << "            #   #                  #   #    " << endl;
         cout << "          #      #               #      #   " << endl;
         cout << "          #      #               #      #   " << endl;
         cout << "          #      #       0       #      #   " << endl;
         cout << "          #      #      -|-      #      #   " << endl;
         cout << "############################################" << endl;
         Sleep(50);
         system("cls");
         cout << "              #                      #      " << endl;
         cout << "            #   #                  #   #    " << endl;
         cout << "          #      #               #      #   " << endl;
         cout << "          #      #               #      #   " << endl;
         cout << "          #      #        0      #      #   " << endl;
         cout << "          #      #       -|-     #      #   " << endl;
         cout << "############################################" << endl;
         Sleep(50);
         system("cls");
         cout << "              #                      #      " << endl;
         cout << "            #   #                  #   #    " << endl;
         cout << "          #      #               #      #   " << endl;
         cout << "          #      #               #      #   " << endl;
         cout << "          #      #         0     #      #   " << endl;
         cout << "          #      #        -|-    #      #   " << endl;
         cout << "############################################" << endl;
         Sleep(50);
         system("cls");
         cout << "              #                      #      " << endl;
         cout << "            #   #                  #   #    " << endl;
         cout << "          #      #               #      #   " << endl;
         cout << "          #      #               #      #   " << endl;
         cout << "          #      #          0    #      #   " << endl;
         cout << "          #      #         -|-   #      #   " << endl;
         cout << "############################################" << endl;
         Sleep(50);
         system("cls");
         cout << "              #                      #      " << endl;
         cout << "            #   #                  #   #    " << endl;
         cout << "          #      #               #      #   " << endl;
         cout << "          #      #               #      #   " << endl;
         cout << "          #      #          0    #      #   " << endl;
         cout << "          #      #         -|-   #      #   " << endl;
         cout << "############################################" << endl;
         Sleep(50);
         system("cls");
         cout << "              #                      #      " << endl;
         cout << "            #   #                  #   #    " << endl;
         cout << "          #      #               #      #   " << endl;
         cout << "          #      #               #      #   " << endl;
         cout << "          #      #           0   #      #   " << endl;
         cout << "          #      #          -|-  #      #   " << endl;
         cout << "############################################" << endl;
         Sleep(50);
         system("cls");
         cout << "              #                      #      " << endl;
         cout << "            #   #                  #   #    " << endl;
         cout << "          #      #               #      #   " << endl;
         cout << "          #      #               #      #   " << endl;
         cout << "          #      #            0  #      #   " << endl;
         cout << "          #      #           -|- #      #   " << endl;
         cout << "############################################" << endl;
         Sleep(50);
         system("cls");
         cout << "              #                      #      " << endl;
         cout << "            #   #                  #   #    " << endl;
         cout << "          #      #               #      #   " << endl;
         cout << "          #      #               #      #   " << endl;
         cout << "          #      #             0 #      #   " << endl;
         cout << "          #      #            -|-#      #   " << endl;
         cout << "############################################" << endl;
         Sleep(50);



     }
}

void lookForTown()
{
    tchance = rand() % 15 + 1;
    if(tchance == 7)
    {
        findSettlement();
    }
}

