#include "zombie.h"
#include "journey.h"
#include <stdio.h>
#include <stdlib.h>
#include <time.h>
#include <iostream>
#include <windows.h>
using namespace std;

int chance;

void encounter()
{
         bool hit;
         bool dead = false;
         int power;
         int swingspeed;
         int hp = 100;
         int zhp = 30;
         int totaldamage;
         int zdamage;
         int action;

         system("COLOR CF");
         cout << "                        " << endl;
         cout << "                        " << endl;
         cout << "                        " << endl;
         cout << "                        " << endl;
         cout << " 0                 0      " << endl;
         cout << "-|-               -|-    " << endl;
         cout << "########################" << endl;
         Sleep(30);
         system("cls");
         cout << "                        " << endl;
         cout << "                        " << endl;
         cout << "                        " << endl;
         cout << "                        " << endl;
         cout << "  0                0        " << endl;
         cout << " -|-              -|-       " << endl;
         cout << "########################" << endl;
         Sleep(30);
         system("cls");
         cout << "                        " << endl;
         cout << "                        " << endl;
         cout << "                        " << endl;
         cout << "                        " << endl;
         cout << "   0               0         " << endl;
         cout << "  -|-             -|-        " << endl;
         cout << "########################" << endl;
         Sleep(30);
         system("cls");
         cout << "                        " << endl;
         cout << "                        " << endl;
         cout << "                        " << endl;
         cout << "                        " << endl;
         cout << "   0               0         " << endl;
         cout << "  -|-             -|-        " << endl;
         cout << "########################" << endl;
         Sleep(30);
         system("cls");
         cout << "                        " << endl;
         cout << "                        " << endl;
         cout << "                        " << endl;
         cout << "                        " << endl;
         cout << "    0              0          " << endl;
         cout << "   -|-            -|-         " << endl;
         cout << "########################" << endl;
         Sleep(30);
         system("cls");
         cout << "                        " << endl;
         cout << "                        " << endl;
         cout << "                        " << endl;
         cout << "                        " << endl;
         cout << "     0             0            " << endl;
         cout << "    -|-           -|-           " << endl;
         cout << "########################" << endl;
         Sleep(30);
         system("cls");
         cout << "                        " << endl;
         cout << "                        " << endl;
         cout << "                        " << endl;
         cout << "                        " << endl;
         cout << "      0            0            " << endl;
         cout << "     -|-          -|-           " << endl;
         cout << "########################" << endl;
         Sleep(30);
         system("cls");
         cout << "                        " << endl;
         cout << "                        " << endl;
         cout << "                        " << endl;
         cout << "                        " << endl;
         cout << "       0           0             " << endl;
         cout << "      -|-         -|-            " << endl;
         cout << "########################" << endl;
         Sleep(30);
         system("cls");
         cout << "                        " << endl;
         cout << "                        " << endl;
         cout << "                        " << endl;
         cout << "                        " << endl;
         cout << "        0           0             " << endl;
         cout << "       -|-         -|-            " << endl;
         cout << "########################" << endl;
         Sleep(30);
         system("cls");
         cout << "                        " << endl;
         cout << "                        " << endl;
         cout << "                        " << endl;
         cout << "                        " << endl;
         cout << "         0          0              " << endl;
         cout << "        -|-        -|-             " << endl;
         cout << "########################" << endl;
         Sleep(30);
         system("cls");
         cout << "                        " << endl;
         cout << "                        " << endl;
         cout << "                        " << endl;
         cout << "                        " << endl;
         cout << "          0         0               " << endl;
         cout << "         -|-       -|-              " << endl;
         cout << "########################" << endl;
         Sleep(30);
         system("cls");
         cout << "                        " << endl;
         cout << "                        " << endl;
         cout << "                        " << endl;
         cout << "                        " << endl;
         cout << "           0        0      " << endl;
         cout << "          -|-      -|-     " << endl;
         cout << "########################" << endl;
         Sleep(30);
         while(dead == false)
         {
          if(zhp <= 0)
          {
          system("cls");
          cout << "                        " << endl;
          cout << "                        " << endl;
          cout << "                        " << endl;
          cout << "                        " << endl;
          cout << "            0       0   " << endl;
          cout << "           -|-     -|-  " << endl;
          cout << "########################" << endl;
          Sleep(30);
          system("cls");
          cout << "                        " << endl;
          cout << "                        " << endl;
          cout << "                        " << endl;
          cout << "                        " << endl;
          cout << "            0           " << endl;
          cout << "           -|-          " << endl;
          cout << "########################" << endl;
          Sleep(30);
          system("cls");
          cout << "                        " << endl;
          cout << "                        " << endl;
          cout << "                        " << endl;
          cout << "                        " << endl;
          cout << "            0       0   " << endl;
          cout << "           -|-     -|-  " << endl;
          cout << "########################" << endl;
          Sleep(30);
          system("cls");
          cout << "                        " << endl;
          cout << "                        " << endl;
          cout << "                        " << endl;
          cout << "                        " << endl;
          cout << "            0           " << endl;
          cout << "           -|-          " << endl;
          cout << "########################" << endl;
          Sleep(30);
          system("cls");
          cout << "                        " << endl;
          cout << "                        " << endl;
          cout << "                        " << endl;
          cout << "                        " << endl;
          cout << "            0       0   " << endl;
          cout << "           -|-     -|-  " << endl;
          cout << "########################" << endl;
          Sleep(30);
          system("cls");
          cout << "                        " << endl;
          cout << "                        " << endl;
          cout << "                        " << endl;
          cout << "                        " << endl;
          cout << "            0           " << endl;
          cout << "           -|-          " << endl;
          cout << "########################" << endl;
          Sleep(30);
          system("cls");
          cout << "                        " << endl;
          cout << "                        " << endl;
          cout << "                        " << endl;
          cout << "                        " << endl;
          cout << "             0          " << endl;
          cout << "            -|-         " << endl;
          cout << "########################" << endl;
          Sleep(30);
          system("cls");
          cout << "                        " << endl;
          cout << "                        " << endl;
          cout << "                        " << endl;
          cout << "                        " << endl;
          cout << "              0          " << endl;
          cout << "             -|-         " << endl;
          cout << "########################" << endl;
          Sleep(30);
          system("cls");
          cout << "                        " << endl;
          cout << "                        " << endl;
          cout << "                        " << endl;
          cout << "                        " << endl;
          cout << "               0        " << endl;
          cout << "              -|-       " << endl;
          cout << "########################" << endl;
          Sleep(30);
          system("cls");
          cout << "                        " << endl;
          cout << "                        " << endl;
          cout << "                        " << endl;
          cout << "                        " << endl;
          cout << "                0        " << endl;
          cout << "               -|-       " << endl;
          cout << "########################" << endl;
          Sleep(30);
          system("cls");
          cout << "                        " << endl;
          cout << "                        " << endl;
          cout << "                        " << endl;
          cout << "                        " << endl;
          cout << "                 0        " << endl;
          cout << "                -|-       " << endl;
          cout << "########################" << endl;
          Sleep(30);
          system("cls");
          cout << "                        " << endl;
          cout << "                        " << endl;
          cout << "                        " << endl;
          cout << "                        " << endl;
          cout << "                  0        " << endl;
          cout << "                 -|-       " << endl;
          cout << "########################" << endl;
          Sleep(30);
          system("cls");
          cout << "                        " << endl;
          cout << "                        " << endl;
          cout << "                        " << endl;
          cout << "                        " << endl;
          cout << "                   0        " << endl;
          cout << "                  -|-       " << endl;
          cout << "########################" << endl;
          Sleep(30);
          system("cls");
          cout << "                        " << endl;
          cout << "                        " << endl;
          cout << "                        " << endl;
          cout << "                        " << endl;
          cout << "                    0        " << endl;
          cout << "                   -|-       " << endl;
          cout << "########################" << endl;
          Sleep(30);
          system("cls");
          cout << "                        " << endl;
          cout << "                        " << endl;
          cout << "                        " << endl;
          cout << "                        " << endl;
          cout << "                     0        " << endl;
          cout << "                    -|-       " << endl;
          cout << "########################" << endl;
          Sleep(30);
          system("cls");
          cout << "                        " << endl;
          cout << "                        " << endl;
          cout << "                        " << endl;
          cout << "                        " << endl;
          cout << "                      0        " << endl;
          cout << "                     -|-       " << endl;
          cout << "########################" << endl;
          Sleep(30);
          system("cls");
          cout << "                        " << endl;
          cout << "                        " << endl;
          cout << "                        " << endl;
          cout << "                        " << endl;
          cout << "                        " << endl;
          cout << "                        " << endl;
          cout << "########################" << endl;
          Sleep(200);
          dead = true;
          walk();
          }
          system("cls");
          cout << "                        " << endl;
          cout << "                        " << endl;
          cout << "                        " << endl;
          cout << "                  "<<zhp<<"/30" << endl;
          cout << "            0       0      " << endl;
          cout << "           -|-     -|-     " << endl;
          cout << "########################" << endl;
          Sleep(30);
          cout << "You encountered a zombie!" << endl;
          cout << "Your hp: " << hp << "/100" << endl;
          cout << "1: Attack" << endl;
          cin >> action;
          if(action == 1)
          {
              power = rand() % 6 + 2;
              swingspeed = rand() % 6 + 1;
              totaldamage = power + swingspeed;
              zhp = zhp - totaldamage;
              zdamage = rand() % 15 + 4;
              hp = hp - zdamage;
              Sleep(90);
              system("cls");
              cout << "                        " << endl;
              cout << "                        " << endl;
              cout << "                    "<<totaldamage<< endl;
              cout << "                 "<< endl;
              cout << "            0       0      " << endl;
              cout << "           -|-     -|-     " << endl;
              cout << "########################" << endl;
              Sleep(90);
              system("cls");
              cout << "                    "<<totaldamage << endl;
              cout << "                        "<< endl;
              cout << "                        "<< endl;
              cout << "            0       0      " << endl;
              cout << "           -|-     -|-     " << endl;
              cout << "########################" << endl;
              Sleep(90);


          }
    }

}
void testChance()
{
    chance = rand() % 20 + 5;
    if(chance == 17)
    {
        encounter();
    }
}
