#include "base.h"
#include "journey.h"
#include "resources.h"
#include "save.h"
#include <stdlib.h>
#include <windows.h>
#include <iostream>
using namespace std;
char choice;
void base()
{
    system("cls");
    system("COLOR 1F");
    clearScreen();
    cout << "########################" << endl;
    cout << "#                      #" << endl;
    cout << "#                       " << endl;
    cout << "#                       " << endl;
    cout << "#                       " << endl;
    cout << "#  0                    " << endl;
    cout << "# -|-                   " << endl;
    cout << "########################" << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << "You are at your base, one of the only safe places in this wasteland. " << endl;
    cout << "Commands: " << endl;
    cout << "L = leave base and enter wasteland. E = Exit";
    cout << endl;
    cin >> choice;
    if(choice == 'L' || choice == 'l')
    {
         system("cls");
         cout << "########################" << endl;
         cout << "#                      #" << endl;
         cout << "#                       " << endl;
         cout << "#                       " << endl;
         cout << "#                       " << endl;
         cout << "#   0                   " << endl;
         cout << "#  -|-                  " << endl;
         cout << "########################" << endl;
         Sleep(30);
         clearScreen();
         cout << "########################" << endl;
         cout << "#                      #" << endl;
         cout << "#                       " << endl;
         cout << "#                       " << endl;
         cout << "#                       " << endl;
         cout << "#    0                  " << endl;
         cout << "#   -|-                 " << endl;
         cout << "########################" << endl;
         Sleep(30);
         clearScreen();
         cout << "########################" << endl;
         cout << "#                      #" << endl;
         cout << "#                       " << endl;
         cout << "#                       " << endl;
         cout << "#                       " << endl;
         cout << "#     0                " << endl;
         cout << "#    -|-               " << endl;
         cout << "########################" << endl;
         Sleep(30);
         clearScreen();
         cout << "########################" << endl;
         cout << "#                      #" << endl;
         cout << "#                       " << endl;
         cout << "#                       " << endl;
         cout << "#                       " << endl;
         cout << "#      0                " << endl;
         cout << "#     -|-               " << endl;
         cout << "########################" << endl;
         Sleep(30);
         clearScreen();
         cout << "########################" << endl;
         cout << "#                      #" << endl;
         cout << "#                       " << endl;
         cout << "#                       " << endl;
         cout << "#                       " << endl;
         cout << "#       0               " << endl;
         cout << "#      -|-              " << endl;
         cout << "########################" << endl;
         Sleep(30);
         clearScreen();
         cout << "########################" << endl;
         cout << "#                      #" << endl;
         cout << "#                       " << endl;
         cout << "#                       " << endl;
         cout << "#                       " << endl;
         cout << "#        0              " << endl;
         cout << "#       -|-             " << endl;
         cout << "########################" << endl;
         Sleep(30);
         clearScreen();
         cout << "########################" << endl;
         cout << "#                      #" << endl;
         cout << "#                       " << endl;
         cout << "#                       " << endl;
         cout << "#                       " << endl;
         cout << "#         0             " << endl;
         cout << "#        -|-            " << endl;
         cout << "########################" << endl;
         Sleep(30);
         clearScreen();
         cout << "########################" << endl;
         cout << "#                      #" << endl;
         cout << "#                       " << endl;
         cout << "#                       " << endl;
         cout << "#                       " << endl;
         cout << "#          0            " << endl;
         cout << "#         -|-           " << endl;
         cout << "########################" << endl;
         Sleep(30);
         clearScreen();
         cout << "########################" << endl;
         cout << "#                      #" << endl;
         cout << "#                       " << endl;
         cout << "#                       " << endl;
         cout << "#                       " << endl;
         cout << "#           0           " << endl;
         cout << "#          -|-          " << endl;
         cout << "########################" << endl;
         Sleep(30);
         clearScreen();
         cout << "########################" << endl;
         cout << "#                      #" << endl;
         cout << "#                       " << endl;
         cout << "#                       " << endl;
         cout << "#                       " << endl;
         cout << "#            0          " << endl;
         cout << "#           -|-         " << endl;
         cout << "########################" << endl;
         Sleep(30);
         clearScreen();
         cout << "########################" << endl;
         cout << "#                      #" << endl;
         cout << "#                       " << endl;
         cout << "#                       " << endl;
         cout << "#                       " << endl;
         cout << "#             0         " << endl;
         cout << "#            -|-        " << endl;
         cout << "########################" << endl;
         Sleep(30);
         clearScreen();
         cout << "########################" << endl;
         cout << "#                      #" << endl;
         cout << "#                       " << endl;
         cout << "#                       " << endl;
         cout << "#                       " << endl;
         cout << "#              0        " << endl;
         cout << "#             -|-       " << endl;
         cout << "########################" << endl;
         Sleep(30);
         clearScreen();
         cout << "########################" << endl;
         cout << "#                      #" << endl;
         cout << "#                       " << endl;
         cout << "#                       " << endl;
         cout << "#                       " << endl;
         cout << "#               0       " << endl;
         cout << "#              -|-      " << endl;
         cout << "########################" << endl;
         Sleep(30);
         clearScreen();
         cout << "########################" << endl;
         cout << "#                      #" << endl;
         cout << "#                       " << endl;
         cout << "#                       " << endl;
         cout << "#                       " << endl;
         cout << "#                0      " << endl;
         cout << "#               -|-     " << endl;
         cout << "########################" << endl;
         Sleep(30);
         clearScreen();
         cout << "########################" << endl;
         cout << "#                      #" << endl;
         cout << "#                       " << endl;
         cout << "#                       " << endl;
         cout << "#                       " << endl;
         cout << "#                 0     " << endl;
         cout << "#                -|-    " << endl;
         cout << "########################" << endl;
         Sleep(30);
         clearScreen();
         cout << "########################" << endl;
         cout << "#                      #" << endl;
         cout << "#                       " << endl;
         cout << "#                       " << endl;
         cout << "#                       " << endl;
         cout << "#                  0    " << endl;
         cout << "#                 -|-   " << endl;
         cout << "########################" << endl;
         Sleep(30);
         clearScreen();
         cout << "########################" << endl;
         cout << "#                      #" << endl;
         cout << "#                       " << endl;
         cout << "#                       " << endl;
         cout << "#                       " << endl;
         cout << "#                   0   " << endl;
         cout << "#                  -|-  " << endl;
         cout << "########################" << endl;
         Sleep(30);
         clearScreen();
         cout << "########################" << endl;
         cout << "#                      #" << endl;
         cout << "#                       " << endl;
         cout << "#                       " << endl;
         cout << "#                       " << endl;
         cout << "#                    0  " << endl;
         cout << "#                   -|- " << endl;
         cout << "########################" << endl;
         Sleep(30);
         clearScreen();
         cout << "########################" << endl;
         cout << "#                      #" << endl;
         cout << "#                       " << endl;
         cout << "#                       " << endl;
         cout << "#                       " << endl;
         cout << "#                     0 " << endl;
         cout << "#                    -|-" << endl;
         cout << "########################" << endl;
         Sleep(30);
         clearScreen();
         cout << "########################" << endl;
         cout << "#                      #" << endl;
         cout << "#                       " << endl;
         cout << "#                       " << endl;
         cout << "#                       " << endl;
         cout << "#                       " << endl;
         cout << "#                       " << endl;
         cout << "########################" << endl;
         Sleep(500);
         walk();

    }
    else if(choice == 'E' || choice == 'e')
    {
     system("cls");
     savegame();
    }
}
