#include "town.h"
#include "journey.h"
#include "resources.h"
#include <iostream>
#include <stdio.h>
#include <stdlib.h>
#include <time.h>
#include <windows.h>
using namespace std;

int tchance;
int tchoice;
void sh()
{
         int fammo;
         int fmedipacks;
         system("cls");
         cout << " ##################  " << endl;
         cout << " #                #  " << endl;
         cout << " #                #  " << endl;
         cout << " #                #  " << endl;
         cout << "  0           %%% #  " << endl;
         cout << " -|-          %%% #  " << endl;
         cout << "###################  " << endl;
         clearScreen();
         Sleep(50);
         cout << " ##################  " << endl;
         cout << " #                #  " << endl;
         cout << " #                #  " << endl;
         cout << " #                #  " << endl;
         cout << "   0          %%% #  " << endl;
         cout << "  -|-         %%% #  " << endl;
         cout << "###################  " << endl;
         clearScreen();
         Sleep(50);
         cout << " ##################  " << endl;
         cout << " #                #  " << endl;
         cout << " #                #  " << endl;
         cout << " #                #  " << endl;
         cout << "    0         %%% #  " << endl;
         cout << "   -|-        %%% #  " << endl;
         cout << "###################  " << endl;
         clearScreen();
         Sleep(50);
         cout << " ##################  " << endl;
         cout << " #                #  " << endl;
         cout << " #                #  " << endl;
         cout << " #                #  " << endl;
         cout << "     0        %%% #  " << endl;
         cout << "    -|-       %%% #  " << endl;
         cout << "###################  " << endl;
         clearScreen();
         Sleep(50);
         cout << " ##################  " << endl;
         cout << " #                #  " << endl;
         cout << " #                #  " << endl;
         cout << " #                #  " << endl;
         cout << "      0       %%% #  " << endl;
         cout << "     -|-      %%% #  " << endl;
         cout << "###################  " << endl;
         clearScreen();
         Sleep(50);
         cout << " ##################  " << endl;
         cout << " #                #  " << endl;
         cout << " #                #  " << endl;
         cout << " #                #  " << endl;
         cout << "       0      %%% #  " << endl;
         cout << "      -|-     %%% #  " << endl;
         cout << "###################  " << endl;
         clearScreen();
         Sleep(50);
         cout << " ##################  " << endl;
         cout << " #                #  " << endl;
         cout << " #                #  " << endl;
         cout << " #                #  " << endl;
         cout << "        0     %%% #  " << endl;
         cout << "       -|-    %%% #  " << endl;
         cout << "###################  " << endl;
         clearScreen();
         Sleep(50);
         cout << " ##################  " << endl;
         cout << " #                #  " << endl;
         cout << " #                #  " << endl;
         cout << " #                #  " << endl;
         cout << "         0    %%% #  " << endl;
         cout << "        -|-   %%% #  " << endl;
         cout << "###################  " << endl;
         clearScreen();
         Sleep(50);
         cout << " ##################  " << endl;
         cout << " #                #  " << endl;
         cout << " #                #  " << endl;
         cout << " #                #  " << endl;
         cout << "          0   %%% #  " << endl;
         cout << "         -|-  %%% #  " << endl;
         cout << "###################  " << endl;
         clearScreen();
         Sleep(50);
         cout << " ##################  " << endl;
         cout << " #                #  " << endl;
         cout << " #                #  " << endl;
         cout << " #                #  " << endl;
         cout << "           0  %%% #  " << endl;
         cout << "          -|- %%% #  " << endl;
         cout << "###################  " << endl;
         clearScreen();
         Sleep(50);
         cout << " ##################  " << endl;
         cout << " #                #  " << endl;
         cout << " #                #  " << endl;
         cout << " #                #  " << endl;
         cout << "            0 %%% #  " << endl;
         cout << "           -|-%%% #  " << endl;
         cout << "###################  " << endl;
         clearScreen();
         int prize = rand() % 3 + 1;
         Sleep(1000);
         clearScreen();
         Sleep(500);
         cout << " ##################  " << endl;
         cout << " #                #  " << endl;
         cout << " #            %   #  " << endl;
         cout << " #             %  #  " << endl;
         cout << "            0   % #  " << endl;
         cout << "           -|-%%% #  " << endl;
         cout << "###################  " << endl;
         clearScreen();
         Sleep(500);
         cout << " ##################  " << endl;
         cout << " #                #  " << endl;
         cout << " #              % #  " << endl;
         cout << " #              % #  " << endl;
         cout << "            0   % #  " << endl;
         cout << "           -|-%%% #  " << endl;
         cout << "###################  " << endl;
         Sleep(500);
         if(prize == 1)
         {
            fammo = rand() % 50 + 25;
            cout << "You found " << fammo << " ammo!" << endl;
            ammo = ammo + fammo;
            system("pause");
            walk();
         }
        else if(prize == 2 || prize == 3)
         {
            fmedipacks = rand() % 4 + 2;
            cout << "You found " << fmedipacks << " medipacks!" << endl;
            medipacks = medipacks + fmedipacks;
            system("pause");
            walk();
         }
}
void findSettlement()
{
         system("cls");
         system("COLOR 1F");
         cout << "              #                      #      " << endl;
         cout << "            #   #                  #   #    " << endl;
         cout << "          #      #               #      #   " << endl;
         cout << "          #      #               #      #   " << endl;
         cout << " 0        #      #               #      #   " << endl;
         cout << "-|-       #      #               #      #   " << endl;
         cout << "############################################" << endl;
         Sleep(50);
         clearScreen();
         cout << "              #                      #      " << endl;
         cout << "            #   #                  #   #    " << endl;
         cout << "          #      #               #      #   " << endl;
         cout << "          #      #               #      #   " << endl;
         cout << "  0       #      #               #      #   " << endl;
         cout << " -|-      #      #               #      #   " << endl;
         cout << "############################################" << endl;
         Sleep(50);
         clearScreen();
         cout << "              #                      #      " << endl;
         cout << "            #   #                  #   #    " << endl;
         cout << "          #      #               #      #   " << endl;
         cout << "          #      #               #      #   " << endl;
         cout << "    0     #      #               #      #   " << endl;
         cout << "   -|-    #      #               #      #   " << endl;
         cout << "############################################" << endl;
         Sleep(50);
         clearScreen();
         cout << "              #                      #      " << endl;
         cout << "            #   #                  #   #    " << endl;
         cout << "          #      #               #      #   " << endl;
         cout << "          #      #               #      #   " << endl;
         cout << "     0    #      #               #      #   " << endl;
         cout << "    -|-   #      #               #      #   " << endl;
         cout << "############################################" << endl;
         cout << "You found an abandoned settlement!" << endl;
         cout << "1: Enter house 1. 2: Enter house 2. 3: Leave settlement" << endl;
         cin >> tchoice;
         if(tchoice == 1)
         {
         Sleep(50);
         clearScreen();
         cout << "              #                      #      " << endl;
         cout << "            #   #                  #   #    " << endl;
         cout << "          #      #               #      #   " << endl;
         cout << "          #      #               #      #   " << endl;
         cout << "     0    #      #               #      #   " << endl;
         cout << "    -|-   #      #               #      #   " << endl;
         cout << "############################################" << endl;
         Sleep(50);
         clearScreen();
         cout << "              #                      #      " << endl;
         cout << "            #   #                  #   #    " << endl;
         cout << "          #      #               #      #   " << endl;
         cout << "          #      #               #      #   " << endl;
         cout << "      0   #      #               #      #   " << endl;
         cout << "     -|-  #      #               #      #   " << endl;
         cout << "############################################" << endl;
         Sleep(50);
         clearScreen();
         cout << "              #                      #      " << endl;
         cout << "            #   #                  #   #    " << endl;
         cout << "          #      #               #      #   " << endl;
         cout << "          #      #               #      #   " << endl;
         cout << "       0  #      #               #      #   " << endl;
         cout << "      -|- #      #               #      #   " << endl;
         cout << "############################################" << endl;
         Sleep(50);
         clearScreen();
         cout << "              #                      #      " << endl;
         cout << "            #   #                  #   #    " << endl;
         cout << "          #      #               #      #   " << endl;
         cout << "          #      #               #      #   " << endl;
         cout << "        0 #      #               #      #   " << endl;
         cout << "       -|-#      #               #      #   " << endl;
         cout << "############################################" << endl;
         Sleep(50);
         clearScreen();
         cout << "              #                      #      " << endl;
         cout << "            #   #                  #   #    " << endl;
         cout << "          #      #               #      #   " << endl;
         cout << "          #      #               #      #   " << endl;
         cout << "          #      #               #      #   " << endl;
         cout << "          #      #               #      #   " << endl;
         cout << "############################################" << endl;
         Sleep(90);
         sh();
         }

         else if(tchoice == 2)
         {
             Sleep(50);
         clearScreen();
         cout << "              #                      #      " << endl;
         cout << "            #   #                  #   #    " << endl;
         cout << "          #      #               #      #   " << endl;
         cout << "          #      #               #      #   " << endl;
         cout << "     0    #      #               #      #   " << endl;
         cout << "    -|-   #      #               #      #   " << endl;
         cout << "############################################" << endl;
         Sleep(50);
         clearScreen();
         cout << "              #                      #      " << endl;
         cout << "            #   #                  #   #    " << endl;
         cout << "          #      #               #      #   " << endl;
         cout << "          #      #               #      #   " << endl;
         cout << "      0   #      #               #      #   " << endl;
         cout << "     -|-  #      #               #      #   " << endl;
         cout << "############################################" << endl;
         Sleep(50);
         clearScreen();
         cout << "              #                      #      " << endl;
         cout << "            #   #                  #   #    " << endl;
         cout << "          #      #               #      #   " << endl;
         cout << "          #      #               #      #   " << endl;
         cout << "       0  #      #               #      #   " << endl;
         cout << "      -|- #      #               #      #   " << endl;
         cout << "############################################" << endl;
         Sleep(50);
         clearScreen();
         cout << "              #                      #      " << endl;
         cout << "            #   #                  #   #    " << endl;
         cout << "          #      #               #      #   " << endl;
         cout << "          #      #               #      #   " << endl;
         cout << "        0 #      #               #      #   " << endl;
         cout << "       -|-#      #               #      #   " << endl;
         cout << "############################################" << endl;
         Sleep(50);
         clearScreen();
         cout << "              #                      #      " << endl;
         cout << "            #   #                  #   #    " << endl;
         cout << "          #      #               #      #   " << endl;
         cout << "          #      #               #      #   " << endl;
         cout << "         0       #               #      #   " << endl;
         cout << "        -|-      #               #      #   " << endl;
         cout << "############################################" << endl;
         Sleep(50);
         clearScreen();
         cout << "              #                      #      " << endl;
         cout << "            #   #                  #   #    " << endl;
         cout << "          #      #               #      #   " << endl;
         cout << "          #      #               #      #   " << endl;
         cout << "          0      #               #      #   " << endl;
         cout << "         -|-     #               #      #   " << endl;
         cout << "############################################" << endl;
         Sleep(50);
         clearScreen();
         cout << "              #                      #      " << endl;
         cout << "            #   #                  #   #    " << endl;
         cout << "          #      #               #      #   " << endl;
         cout << "          #      #               #      #   " << endl;
         cout << "           0     #               #      #   " << endl;
         cout << "          -|-    #               #      #   " << endl;
         cout << "############################################" << endl;
         Sleep(50);
         clearScreen();
         cout << "              #                      #      " << endl;
         cout << "            #   #                  #   #    " << endl;
         cout << "          #      #               #      #   " << endl;
         cout << "          #      #               #      #   " << endl;
         cout << "          #  0   #               #      #   " << endl;
         cout << "          # -|-  #               #      #   " << endl;
         cout << "############################################" << endl;
         Sleep(50);
         clearScreen();
         cout << "              #                      #      " << endl;
         cout << "            #   #                  #   #    " << endl;
         cout << "          #      #               #      #   " << endl;
         cout << "          #      #               #      #   " << endl;
         cout << "          #   0  #               #      #   " << endl;
         cout << "          #  -|- #               #      #   " << endl;
         cout << "############################################" << endl;
         Sleep(50);
         clearScreen();
         cout << "              #                      #      " << endl;
         cout << "            #   #                  #   #    " << endl;
         cout << "          #      #               #      #   " << endl;
         cout << "          #      #               #      #   " << endl;
         cout << "          #    0 #               #      #   " << endl;
         cout << "          #   -|-#               #      #   " << endl;
         cout << "############################################" << endl;
         Sleep(50);
         clearScreen();
         cout << "              #                      #      " << endl;
         cout << "            #   #                  #   #    " << endl;
         cout << "          #      #               #      #   " << endl;
         cout << "          #      #               #      #   " << endl;
         cout << "          #     0                #      #   " << endl;
         cout << "          #    -|-               #      #   " << endl;
         cout << "############################################" << endl;
         Sleep(50);
         clearScreen();
         cout << "              #                      #      " << endl;
         cout << "            #   #                  #   #    " << endl;
         cout << "          #      #               #      #   " << endl;
         cout << "          #      #               #      #   " << endl;
         cout << "          #      0               #      #   " << endl;
         cout << "          #     -|-              #      #   " << endl;
         cout << "############################################" << endl;
         Sleep(50);
         clearScreen();
         cout << "              #                      #      " << endl;
         cout << "            #   #                  #   #    " << endl;
         cout << "          #      #               #      #   " << endl;
         cout << "          #      #               #      #   " << endl;
         cout << "          #       0              #      #   " << endl;
         cout << "          #      -|-             #      #   " << endl;
         cout << "############################################" << endl;
         Sleep(50);
         clearScreen();
         cout << "              #                      #      " << endl;
         cout << "            #   #                  #   #    " << endl;
         cout << "          #      #               #      #   " << endl;
         cout << "          #      #               #      #   " << endl;
         cout << "          #      # 0             #      #   " << endl;
         cout << "          #      #-|-            #      #   " << endl;
         cout << "############################################" << endl;
         Sleep(50);
         clearScreen();
         cout << "              #                      #      " << endl;
         cout << "            #   #                  #   #    " << endl;
         cout << "          #      #               #      #   " << endl;
         cout << "          #      #               #      #   " << endl;
         cout << "          #      #  0            #      #   " << endl;
         cout << "          #      # -|-           #      #   " << endl;
         cout << "############################################" << endl;
         Sleep(50);
         clearScreen();
         cout << "              #                      #      " << endl;
         cout << "            #   #                  #   #    " << endl;
         cout << "          #      #               #      #   " << endl;
         cout << "          #      #               #      #   " << endl;
         cout << "          #      #   0           #      #   " << endl;
         cout << "          #      #  -|-          #      #   " << endl;
         cout << "############################################" << endl;
         Sleep(50);
         clearScreen();
         cout << "              #                      #      " << endl;
         cout << "            #   #                  #   #    " << endl;
         cout << "          #      #               #      #   " << endl;
         cout << "          #      #               #      #   " << endl;
         cout << "          #      #    0          #      #   " << endl;
         cout << "          #      #   -|-         #      #   " << endl;
         cout << "############################################" << endl;
         Sleep(50);
         clearScreen();
         cout << "              #                      #      " << endl;
         cout << "            #   #                  #   #    " << endl;
         cout << "          #      #               #      #   " << endl;
         cout << "          #      #               #      #   " << endl;
         cout << "          #      #     0         #      #   " << endl;
         cout << "          #      #    -|-        #      #   " << endl;
         cout << "############################################" << endl;
         Sleep(50);
         clearScreen();
         cout << "              #                      #      " << endl;
         cout << "            #   #                  #   #    " << endl;
         cout << "          #      #               #      #   " << endl;
         cout << "          #      #               #      #   " << endl;
         cout << "          #      #      0        #      #   " << endl;
         cout << "          #      #     -|-       #      #   " << endl;
         cout << "############################################" << endl;
         Sleep(50);
         clearScreen();
         cout << "              #                      #      " << endl;
         cout << "            #   #                  #   #    " << endl;
         cout << "          #      #               #      #   " << endl;
         cout << "          #      #               #      #   " << endl;
         cout << "          #      #       0       #      #   " << endl;
         cout << "          #      #      -|-      #      #   " << endl;
         cout << "############################################" << endl;
         Sleep(50);
         clearScreen();
         cout << "              #                      #      " << endl;
         cout << "            #   #                  #   #    " << endl;
         cout << "          #      #               #      #   " << endl;
         cout << "          #      #               #      #   " << endl;
         cout << "          #      #        0      #      #   " << endl;
         cout << "          #      #       -|-     #      #   " << endl;
         cout << "############################################" << endl;
         Sleep(50);
         clearScreen();
         cout << "              #                      #      " << endl;
         cout << "            #   #                  #   #    " << endl;
         cout << "          #      #               #      #   " << endl;
         cout << "          #      #               #      #   " << endl;
         cout << "          #      #         0     #      #   " << endl;
         cout << "          #      #        -|-    #      #   " << endl;
         cout << "############################################" << endl;
         Sleep(50);
         clearScreen();
         cout << "              #                      #      " << endl;
         cout << "            #   #                  #   #    " << endl;
         cout << "          #      #               #      #   " << endl;
         cout << "          #      #               #      #   " << endl;
         cout << "          #      #          0    #      #   " << endl;
         cout << "          #      #         -|-   #      #   " << endl;
         cout << "############################################" << endl;
         Sleep(50);
         clearScreen();
         cout << "              #                      #      " << endl;
         cout << "            #   #                  #   #    " << endl;
         cout << "          #      #               #      #   " << endl;
         cout << "          #      #               #      #   " << endl;
         cout << "          #      #          0    #      #   " << endl;
         cout << "          #      #         -|-   #      #   " << endl;
         cout << "############################################" << endl;
         Sleep(50);
         clearScreen();
         cout << "              #                      #      " << endl;
         cout << "            #   #                  #   #    " << endl;
         cout << "          #      #               #      #   " << endl;
         cout << "          #      #               #      #   " << endl;
         cout << "          #      #           0   #      #   " << endl;
         cout << "          #      #          -|-  #      #   " << endl;
         cout << "############################################" << endl;
         Sleep(50);
         clearScreen();
         cout << "              #                      #      " << endl;
         cout << "            #   #                  #   #    " << endl;
         cout << "          #      #               #      #   " << endl;
         cout << "          #      #               #      #   " << endl;
         cout << "          #      #            0  #      #   " << endl;
         cout << "          #      #           -|- #      #   " << endl;
         cout << "############################################" << endl;
         Sleep(50);
         clearScreen();
         cout << "              #                      #      " << endl;
         cout << "            #   #                  #   #    " << endl;
         cout << "          #      #               #      #   " << endl;
         cout << "          #      #               #      #   " << endl;
         cout << "          #      #             0 #      #   " << endl;
         cout << "          #      #            -|-#      #   " << endl;
         cout << "############################################" << endl;
         Sleep(50);
         sh();


     }
}

void lookForTown()
{
    tchance = rand() % 15 + 1;
    if(tchance == 1 || tchance == 6)
    {
        findSettlement();
    }
}
